### ISSUE TITLE
Clean up previews

### ISSUE THREAD

**Issue by Anddor** [szeestraten/kidsakoder-minecraft#207] opened 2016-05-05 07:05 UTC

**Comment by Anddor** [comment] 2016-05-05 07:05
Old previews create trouble when overviewer thinks they are previous renders of new worlds (world._id is reused). They should be cleaned up when a world is deleted.

**Comment by DeimosA** [comment] 2016-05-05 13:15
Possible duplicate of #156

**Closed** 2016-05-06 08:02 UTC
